<?php

namespace AppBundle\Repository;

/**
 * RateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RateRepository extends \Doctrine\ORM\EntityRepository
{
    public function getPriceAndRate($age) {
        // Création de l'alias
        $qb = $this->createQueryBuilder('r');

        // Recherche d'un tarif par rapport à un âge
        $qb->where('r.minAge <= :age')->andWhere('r.maxAge >= :age')->setParameter('age', $age);

        // Récupération du résultat
        $results = $qb->getQuery()->getResult();

        // Retourne le résultat
        return $results[0];
    }
}
